<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        // Random date helper: Jan–Apr 2026, skewed so later months have more orders
        $rd = function (int $month, int $dayMin = 1, int $dayMax = 28): Carbon {
            return Carbon::create(2026, $month, rand($dayMin, $dayMax), rand(8, 22), rand(0, 59), 0);
        };

        DB::table('users')->insert([
            ['id' => 1, 'name' => 'Budi Santoso', 'email' => 'budi@email.com', 'password' => Hash::make('password123'), 'role' => 'user', 'address' => 'Jl. Merdeka No. 123', 'city' => 'Jakarta', 'postal_code' => '10110', 'last_access' => $now],
            ['id' => 2, 'name' => 'Siti Aminah', 'email' => 'siti@email.com', 'password' => Hash::make('rahasia321'), 'role' => 'user', 'address' => 'Jl. Mawar No. 45', 'city' => 'Bandung', 'postal_code' => '40115', 'last_access' => $now],
            ['id' => 3, 'name' => 'Admin Utama', 'email' => 'admin@toko.com', 'password' => Hash::make('adminpass'), 'role' => 'admin', 'address' => 'Gedung Perkantoran Sudirman', 'city' => 'Jakarta', 'postal_code' => '12190', 'last_access' => $now],
            ['id' => 4, 'name' => 'Rina Melati', 'email' => 'rina@email.com', 'password' => Hash::make('passrina'), 'role' => 'user', 'address' => 'Jl. Melati No. 67', 'city' => 'Surabaya', 'postal_code' => '60111', 'last_access' => $now],
            ['id' => 5, 'name' => 'Andi Wijaya', 'email' => 'andi@email.com', 'password' => Hash::make('andi1234'), 'role' => 'user', 'address' => 'Jl. Anggrek No. 89', 'city' => 'Medan', 'postal_code' => '20111', 'last_access' => $now],
            ['id' => 6, 'name' => 'Citra Kirana', 'email' => 'citra@email.com', 'password' => Hash::make('citra123'), 'role' => 'user', 'address' => 'Jl. Tulip No. 12', 'city' => 'Semarang', 'postal_code' => '50111', 'last_access' => $now],
            ['id' => 7, 'name' => 'Dodi Pratama', 'email' => 'dodi@email.com', 'password' => Hash::make('dodi123'), 'role' => 'user', 'address' => 'Jl. Kamboja No. 34', 'city' => 'Yogyakarta', 'postal_code' => '55111', 'last_access' => $now],
            ['id' => 8, 'name' => 'Eka Putri', 'email' => 'eka@email.com', 'password' => Hash::make('eka123'), 'role' => 'user', 'address' => 'Jl. Teratai No. 56', 'city' => 'Makassar', 'postal_code' => '90111', 'last_access' => $now],
            ['id' => 9, 'name' => 'Faisal Reza', 'email' => 'faisal@email.com', 'password' => Hash::make('faisal123'), 'role' => 'user', 'address' => 'Jl. Matahari No. 78', 'city' => 'Palembang', 'postal_code' => '30111', 'last_access' => $now],
            ['id' => 10, 'name' => 'Admin Kedua', 'email' => 'admin2@toko.com', 'password' => Hash::make('adminpass2'), 'role' => 'admin', 'address' => 'Gedung ITC Kuningan', 'city' => 'Jakarta', 'postal_code' => '12940', 'last_access' => $now],
            ['id' => 11, 'name' => 'Galih Purnomo', 'email' => 'galih@email.com', 'password' => Hash::make('galih123'), 'role' => 'user', 'address' => 'Jl. Dahlia No. 90', 'city' => 'Denpasar', 'postal_code' => '80111', 'last_access' => $now],
            ['id' => 12, 'name' => 'Hani Syaputri', 'email' => 'hani@email.com', 'password' => Hash::make('hani123'), 'role' => 'user', 'address' => 'Jl. Sakura No. 23', 'city' => 'Batam', 'postal_code' => '29411', 'last_access' => $now],
            ['id' => 13, 'name' => 'Irfan Hakim', 'email' => 'irfan@email.com', 'password' => Hash::make('irfan123'), 'role' => 'user', 'address' => 'Jl. Kenanga No. 45', 'city' => 'Malang', 'postal_code' => '65111', 'last_access' => $now],
            ['id' => 14, 'name' => 'Julia Perez', 'email' => 'julia@email.com', 'password' => Hash::make('julia123'), 'role' => 'user', 'address' => 'Jl. Flamboyan No. 67', 'city' => 'Solo', 'postal_code' => '57111', 'last_access' => $now],
            ['id' => 15, 'name' => 'Kevin Sanjaya', 'email' => 'kevin@email.com', 'password' => Hash::make('kevin123'), 'role' => 'user', 'address' => 'Jl. Bougainville No. 89', 'city' => 'Balikpapan', 'postal_code' => '76111', 'last_access' => $now],
            ['id' => 16, 'name' => 'Lestari Indah', 'email' => 'lestari@email.com', 'password' => Hash::make('lestari123'), 'role' => 'user', 'address' => 'Jl. Cempaka No. 12', 'city' => 'Manado', 'postal_code' => '95111', 'last_access' => $now],
            ['id' => 17, 'name' => 'Mamat Alkatiri', 'email' => 'mamat@email.com', 'password' => Hash::make('mamat123'), 'role' => 'user', 'address' => 'Jl. Anyelir No. 34', 'city' => 'Ambon', 'postal_code' => '97111', 'last_access' => $now],
            ['id' => 18, 'name' => 'Nia Ramadhani', 'email' => 'nia@email.com', 'password' => Hash::make('nia123'), 'role' => 'user', 'address' => 'Jl. Lavender No. 56', 'city' => 'Pontianak', 'postal_code' => '78111', 'last_access' => $now],
            ['id' => 19, 'name' => 'Oki Setiana', 'email' => 'oki@email.com', 'password' => Hash::make('oki123'), 'role' => 'user', 'address' => 'Jl. Edelweis No. 78', 'city' => 'Samarinda', 'postal_code' => '75111', 'last_access' => $now],
            ['id' => 20, 'name' => 'Pandu Winata', 'email' => 'pandu@email.com', 'password' => Hash::make('pandu123'), 'role' => 'user', 'address' => 'Jl. Aster No. 90', 'city' => 'Pekanbaru', 'postal_code' => '28111', 'last_access' => $now],
        ]);

        DB::table('genres')->insert([
            ['id' => 1, 'name' => 'Fiksi', 'description' => 'Cerita rekaan yang tidak berdasarkan kenyataan sejarah.'],
            ['id' => 2, 'name' => 'Fantasi', 'description' => 'Genre yang menggunakan sihir atau elemen supranatural.'],
            ['id' => 3, 'name' => 'Komedi', 'description' => 'Genre yang bertujuan untuk memancing tawa pembaca.'],
            ['id' => 4, 'name' => 'Biografi', 'description' => 'Kisah perjalanan hidup seseorang tokoh.'],
            ['id' => 5, 'name' => 'Sejarah', 'description' => 'Cerita yang berlatar belakang peristiwa sejarah masa lampau.'],
            ['id' => 6, 'name' => 'Horor', 'description' => 'Cerita yang bertujuan menimbulkan rasa takut.'],
            ['id' => 7, 'name' => 'Romansa', 'description' => 'Kisah yang berfokus pada hubungan asmara.'],
            ['id' => 8, 'name' => 'Misteri', 'description' => 'Kisah tentang pemecahan teka-teki atau kejahatan.'],
            ['id' => 9, 'name' => 'Thriler', 'description' => 'Kisah yang menegangkan dan memacu adrenalin.'],
            ['id' => 10, 'name' => 'Sains', 'description' => 'Buku yang membahas pengetahuan ilmiah secara faktual atau fiksi.'],
            ['id' => 11, 'name' => 'Petualangan', 'description' => 'Kisah tentang sebuah perjalanan heroik.'],
            ['id' => 12, 'name' => 'Puisi', 'description' => 'Karya sastra yang mengutamakan keindahan bahasa.'],
            ['id' => 13, 'name' => 'Dongeng', 'description' => 'Cerita fiktif tentang hal-hal gaib.'],
            ['id' => 14, 'name' => 'Distopia', 'description' => 'Cerita tentang dunia yang kacau dan menakutkan.'],
            ['id' => 15, 'name' => 'Esei', 'description' => 'Karangan prosa yang membahas suatu masalah.'],
            ['id' => 16, 'name' => 'Agama', 'description' => 'Buku yang membahas tentang ajaran religius.'],
            ['id' => 17, 'name' => 'Filsafat', 'description' => 'Buku mengenai pemikiran dan kebijaksanaan.'],
            ['id' => 18, 'name' => 'Psikologi', 'description' => 'Buku yang membahas kejiwaan dan perilaku.'],
            ['id' => 19, 'name' => 'Hukum', 'description' => 'Buku yang berkaitan dengan sistem peradilan.'],
            ['id' => 20, 'name' => 'Ekonomi', 'description' => 'Buku seputar keuangan, bisnis, dan perdagangan.'],
        ]);

        DB::table('authors')->insert([
            ['id' => 1, 'name' => 'Andrea Hirata', 'photo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Andrea_Hirata.jpg/330px-Andrea_Hirata.jpg', 'bio' => 'Penulis novel Laskar Pelangi.'],
            ['id' => 2, 'name' => 'Tere Liye', 'photo' => 'https://www.tereliye.net/wp-content/uploads/2021/03/Tere-Liye.jpg', 'bio' => 'Penulis buku fiksi populer Indonesia.'],
            ['id' => 3, 'name' => 'J.K. Rowling', 'photo' => 'https://upload.wikimedia.org/wikipedia/commons/5/5d/J._K._Rowling_2010.jpg', 'bio' => 'Penulis seri Harry Potter.'],
            ['id' => 4, 'name' => 'Pramoedya Ananta Toer', 'photo' => 'https://upload.wikimedia.org/wikipedia/commons/7/79/Pramoedya_Ananta_Toer_Kesusastraan_Indonesia_Modern_dalam_Kritik_dan_Essai_1_%281962%29_p136.jpg', 'bio' => 'Sastrawan besar Indonesia.'],
            ['id' => 5, 'name' => 'Raditya Dika', 'photo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Raditya_Dika_on_Interview_GoGirl_TV.jpg/330px-Raditya_Dika_on_Interview_GoGirl_TV.jpg', 'bio' => 'Penulis buku komedi dan sutradara.'],
            ['id' => 6, 'name' => 'Dee Lestari', 'photo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Dewi_Lestari.JPG/330px-Dewi_Lestari.JPG', 'bio' => 'Penulis novel Supernova.'],
            ['id' => 7, 'name' => 'Stephen King', 'photo' => 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Stephen_King%2C_Comicon.jpg', 'bio' => 'Raja novel horor dan supranatural dunia.'],
            ['id' => 8, 'name' => 'Agatha Christie', 'photo' => 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Agatha_Christie_in_Nederland_%28detectiveschrijfster%29%2C_bij_aankomst_op_Schiphol_me%2C_Bestanddeelnr_916-8898_%28cropped%29.jpg', 'bio' => 'Ratu novel misteri detektif asal Inggris.'],
            ['id' => 9, 'name' => 'Ahmad Fuadi', 'photo' => 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Ahmad_Fuadi.jpg', 'bio' => 'Penulis novel Negeri 5 Menara.'],
            ['id' => 10, 'name' => 'Eka Kurniawan', 'photo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Eka_Kurniawan%2C_DSC_0071B.jpg/330px-Eka_Kurniawan%2C_DSC_0071B.jpg', 'bio' => 'Novelis dari berbagai genre seperti fiksi sejarah.'],
            ['id' => 11, 'name' => 'J.R.R. Tolkien', 'photo' => 'https://upload.wikimedia.org/wikipedia/commons/d/d4/J._R._R._Tolkien%2C_ca._1925.jpg', 'bio' => 'Penulis The Lord of the Rings.'],
            ['id' => 12, 'name' => 'George R.R. Martin', 'photo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/George_R._R._Martin_%2854743316729%29.jpg/330px-George_R._R._Martin_%2854743316729%29.jpg', 'bio' => 'Penulis seri A Song of Ice and Fire.'],
            ['id' => 13, 'name' => 'Haruki Murakami', 'photo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Conversatorio_Haruki_Murakami_%2812_ de_12%29_%2845747009452%29_%28cropped%29.jpg/330px-Conversatorio_Haruki_Murakami_%2812_de_12%29_%2845747009452%29_%28cropped%29.jpg', 'bio' => 'Penulis novel surealis dari Jepang.'],
            ['id' => 14, 'name' => 'R.A. Kartini', 'photo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/COLLECTIE_TROPENMUSEUM_Portret_van_Raden_Ajeng_Kartini_TMnr_10018776.jpg/330px-COLLECTIE_TROPENMUSEUM_Portret_van_Raden_Ajeng_Kartini_TMnr_10018776.jpg', 'bio' => 'Pahlawan nasional dan penulis surat-surat.'],
            ['id' => 15, 'name' => 'Dan Brown', 'photo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/N%C3%A1v%C3%A1t%C4%9Bva_Dana_Browna_v_NK_%C4%8CR_17._-_18._2025_03_%28cropped%29.jpg/330px-N%C3%A1v%C3%A1t%C4%9Bva_Dana_Browna_v_NK_%C4%8CR_17._-_18._2025_03_%28cropped%29.jpg', 'bio' => 'Penulis novel The Da Vinci Code.'],
            ['id' => 16, 'name' => 'Arthur Conan Doyle', 'photo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Arthur_Conan_Doyle_by_Walter_Benington%2C_1914.png/330px-Arthur_Conan_Doyle_by_Walter_Benington%2C_1914.png', 'bio' => 'Pencipta karakter Sherlock Holmes.'],
            ['id' => 17, 'name' => 'Mark Twain', 'photo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Mark_Twain_by_AF_Bradley.jpg/330px-Mark_Twain_by_AF_Bradley.jpg', 'bio' => 'Penulis petualangan Amerika klasik.'],
            ['id' => 18, 'name' => 'Jane Austen', 'photo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/CassandraAusten-JaneAusten%28c.1810%29_hires.jpg/330px-CassandraAusten-JaneAusten%28c.1810%29_hires.jpg', 'bio' => 'Penulis novel romantis klasik Inggris.'],
            ['id' => 19, 'name' => 'Gillian Flynn', 'photo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Gillian_Flynn_2014_%28cropped%29.jpg/330px-Gillian_Flynn_2014_%28cropped%29.jpg', 'bio' => 'Penulis novel thriller fenomenal.'],
            ['id' => 20, 'name' => 'Fiersa Besari', 'photo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Fiersa_Besari_at_the_Mata_Najwa_eps._Kita_Bisa_Apa.png/330px-Fiersa_Besari_at_the_Mata_Najwa_eps._Kita_Bisa_Apa.png', 'bio' => 'Musisi dan penulis buku romansa petualangan.'],
        ]);

        DB::table('books')->insert([
            ['id' => 1, 'title' => 'Laskar Pelangi', 'description' => 'Kisah 10 anak di Belitung.', 'price' => 80000.00, 'stock' => 29, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://upload.wikimedia.org/wikipedia/id/8/8e/Laskar_pelangi_sampul.jpg', 'genre_id' => 1, 'author_id' => 1],
            ['id' => 2, 'title' => 'Bumi', 'description' => 'Petualangan Raib di dunia paralel.', 'price' => 85000.00, 'stock' => 15, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://upload.wikimedia.org/wikipedia/id/4/49/Bumi_%28sampul%29.jpg', 'genre_id' => 2, 'author_id' => 2],
            ['id' => 3, 'title' => 'Harry Potter dan Batu Bertuah', 'description' => 'Awal kisah penyihir cilik.', 'price' => 150000.00, 'stock' => 20, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/id/10580458-L.jpg', 'genre_id' => 2, 'author_id' => 3],
            ['id' => 4, 'title' => 'Bumi Manusia', 'description' => 'Kisah cinta Minke dan Annelies.', 'price' => 120000.00, 'stock' => 8, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/id/15122195-L.jpg', 'genre_id' => 5, 'author_id' => 4],
            ['id' => 5, 'title' => 'Kambing Jantan', 'description' => 'Catatan harian pelajar bodoh.', 'price' => 60000.00, 'stock' => 24, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://bukukita.com/babacms/displaybuku/6514_f.jpg', 'genre_id' => 3, 'author_id' => 5],
            ['id' => 6, 'title' => 'Supernova', 'description' => 'Fiksi sains tentang dinamika romansa.', 'price' => 95000.00, 'stock' => 12, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1348063834i/11960914.jpg', 'genre_id' => 10, 'author_id' => 6],
            ['id' => 7, 'title' => 'The Shining', 'description' => 'Kisah keluarga yang terjebak di hotel angker.', 'price' => 110000.00, 'stock' => 5, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/id/12376585-L.jpg', 'genre_id' => 6, 'author_id' => 7],
            ['id' => 8, 'title' => 'Murder on the Orient Express', 'description' => 'Pembunuhan di atas kereta.', 'price' => 105000.00, 'stock' => 18, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/id/11100465-L.jpg', 'genre_id' => 8, 'author_id' => 8],
            ['id' => 9, 'title' => 'Negeri 5 Menara', 'description' => 'Kisah 6 santri yang mengejar impian.', 'price' => 88000.00, 'stock' => 30, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1249749162i/6688121.jpg', 'genre_id' => 1, 'author_id' => 9],
            ['id' => 10, 'title' => 'Cantik Itu Luka', 'description' => 'Realisme magis sejarah epik.', 'price' => 125000.00, 'stock' => 10, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://upload.wikimedia.org/wikipedia/id/d/d2/CiL_%28sampul%29.jpg', 'genre_id' => 5, 'author_id' => 10],
            ['id' => 11, 'title' => 'The Lord of the Rings', 'description' => 'Cerita epik para pembawa cincin.', 'price' => 250000.00, 'stock' => 22, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/id/14625765-L.jpg', 'genre_id' => 2, 'author_id' => 11],
            ['id' => 12, 'title' => 'A Game of Thrones', 'description' => 'Perebutan takhta di benua Westeros.', 'price' => 180000.00, 'stock' => 14, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/id/9269962-L.jpg', 'genre_id' => 2, 'author_id' => 12],
            ['id' => 13, 'title' => 'Norwegian Wood', 'description' => 'Kisah cinta yang muram bergaya surealis.', 'price' => 90000.00, 'stock' => 16, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/id/2237620-L.jpg', 'genre_id' => 7, 'author_id' => 13],
            ['id' => 14, 'title' => 'Habis Gelap Terbitlah Terang', 'description' => 'Kumpulan surat perjuangan memajukan wanita.', 'price' => 70000.00, 'stock' => 35, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Door_duisternis_tot_licht_1st_edition_cover.jpg/330px-Door_duisternis_tot_licht_1st_edition_cover.jpg', 'genre_id' => 4, 'author_id' => 14],
            ['id' => 15, 'title' => 'The Da Vinci Code', 'description' => 'Pencarian cawan suci dan teori konspirasi.', 'price' => 135000.00, 'stock' => 19, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/id/9255229-L.jpg', 'genre_id' => 8, 'author_id' => 15],
            ['id' => 16, 'title' => 'Sherlock Holmes', 'description' => 'Petualangan detektif paling terkenal.', 'price' => 115000.00, 'stock' => 25, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/id/6717853-L.jpg', 'genre_id' => 8, 'author_id' => 16],
            ['id' => 17, 'title' => 'The Adventures of Tom Sawyer', 'description' => 'Kisah seorang anak lelaki yang cerdik.', 'price' => 75000.00, 'stock' => 11, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/id/12043351-L.jpg', 'genre_id' => 11, 'author_id' => 17],
            ['id' => 18, 'title' => 'Pride and Prejudice', 'description' => 'Kritik sosial tentang pernikahan di Inggris.', 'price' => 85000.00, 'stock' => 21, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/id/14348537-L.jpg', 'genre_id' => 7, 'author_id' => 18],
            ['id' => 19, 'title' => 'Gone Girl', 'description' => 'Kisah istri yang menghilang misterius.', 'price' => 95000.00, 'stock' => 17, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/id/8368314-L.jpg', 'genre_id' => 9, 'author_id' => 19],
            ['id' => 20, 'title' => 'Garis Waktu', 'description' => 'Cerita kenangan dan waktu.', 'price' => 65000.00, 'stock' => 28, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://cdn.gramedia.com/uploads/items/Garis_waktu.jpg', 'genre_id' => 7, 'author_id' => 20],

            // --- 30 buku tambahan ---
            ['id' => 21, 'title' => 'Harry Potter dan Kamar Rahasia', 'description' => 'Harry menghadapi ancaman misterius di Hogwarts tahun kedua.', 'price' => 155000.00, 'stock' => 18, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/isbn/9780439064873-L.jpg', 'genre_id' => 2, 'author_id' => 3],
            ['id' => 22, 'title' => 'Harry Potter dan Tawanan Azkaban', 'description' => 'Harry mengungkap rahasia tawanan berbahaya dari masa lalu.', 'price' => 155000.00, 'stock' => 14, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/isbn/9780439655484-L.jpg', 'genre_id' => 2, 'author_id' => 3],
            ['id' => 23, 'title' => 'The Green Mile', 'description' => 'Kisah penjaga sel maut dan tahanan yang memiliki kekuatan ajaib.', 'price' => 130000.00, 'stock' => 12, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/isbn/9781501160844-L.jpg', 'genre_id' => 1, 'author_id' => 7],
            ['id' => 24, 'title' => 'IT', 'description' => 'Tujuh anak menghadapi entitas jahat yang menjelma sebagai badut.', 'price' => 145000.00, 'stock' => 8, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/isbn/9781501142970-L.jpg', 'genre_id' => 6, 'author_id' => 7],
            ['id' => 25, 'title' => 'And Then There Were None', 'description' => 'Sepuluh orang terjebak di pulau terpencil dan mati satu per satu.', 'price' => 98000.00, 'stock' => 20, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/isbn/9780062073488-L.jpg', 'genre_id' => 8, 'author_id' => 8],
            ['id' => 26, 'title' => 'Death on the Nile', 'description' => 'Hercule Poirot menyelidiki pembunuhan di atas kapal pesiar Sungai Nil.', 'price' => 92000.00, 'stock' => 15, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/isbn/9780062073480-L.jpg', 'genre_id' => 8, 'author_id' => 8],
            ['id' => 27, 'title' => 'Inferno', 'description' => 'Robert Langdon memecahkan teka-teki berbasis karya Dante untuk mencegah bencana.', 'price' => 140000.00, 'stock' => 13, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/isbn/9780385537858-L.jpg', 'genre_id' => 9, 'author_id' => 15],
            ['id' => 28, 'title' => 'Angels and Demons', 'description' => 'Robert Langdon menyelamatkan Vatikan dari ancaman Illuminati.', 'price' => 128000.00, 'stock' => 16, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/isbn/9781416524793-L.jpg', 'genre_id' => 9, 'author_id' => 15],
            ['id' => 29, 'title' => 'The Hobbit', 'description' => 'Bilbo Baggins memulai petualangan epik bersama para kurcaci dan naga.', 'price' => 160000.00, 'stock' => 19, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg', 'genre_id' => 2, 'author_id' => 11],
            ['id' => 30, 'title' => 'Kafka on the Shore', 'description' => 'Kisah paralel remaja pelarian dan seorang lansia yang bisa berbicara dengan kucing.', 'price' => 115000.00, 'stock' => 14, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/isbn/9781400079278-L.jpg', 'genre_id' => 1, 'author_id' => 13],
            ['id' => 31, 'title' => '1Q84', 'description' => 'Cerita dunia paralel yang misterius dengan dua bulan di langit.', 'price' => 185000.00, 'stock' => 10, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/isbn/9780307476463-L.jpg', 'genre_id' => 1, 'author_id' => 13],
            ['id' => 32, 'title' => 'Sense and Sensibility', 'description' => 'Kisah dua saudari dengan kepribadian berbeda dalam mencari cinta sejati.', 'price' => 80000.00, 'stock' => 22, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/isbn/9780141040349-L.jpg', 'genre_id' => 7, 'author_id' => 18],
            ['id' => 33, 'title' => 'Sharp Objects', 'description' => 'Reporter kembali ke kampung halaman untuk menyelidiki serangkaian pembunuhan.', 'price' => 92000.00, 'stock' => 17, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/isbn/9780307341556-L.jpg', 'genre_id' => 9, 'author_id' => 19],
            ['id' => 34, 'title' => 'A Clash of Kings', 'description' => 'Perang saudara melanda tujuh kerajaan Westeros yang tak berkesudahan.', 'price' => 175000.00, 'stock' => 11, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/isbn/9780553579901-L.jpg', 'genre_id' => 2, 'author_id' => 12],
            ['id' => 35, 'title' => 'Adventures of Huckleberry Finn', 'description' => 'Huck Finn melarikan diri bersama Jim mengarungi Sungai Mississippi.', 'price' => 72000.00, 'stock' => 25, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/isbn/9780486280615-L.jpg', 'genre_id' => 11, 'author_id' => 17],
            ['id' => 36, 'title' => 'Pet Sematary', 'description' => 'Keluarga yang pindah ke rumah dekat pemakaman binatang yang menyimpan rahasia gelap.', 'price' => 138000.00, 'stock' => 9, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/isbn/9781982101947-L.jpg', 'genre_id' => 6, 'author_id' => 7],
            ['id' => 37, 'title' => 'A Storm of Swords', 'description' => 'Pertempuran dan pengkhianatan di Westeros semakin brutal.', 'price' => 180000.00, 'stock' => 8, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/isbn/9780553573428-L.jpg', 'genre_id' => 2, 'author_id' => 12],
            ['id' => 38, 'title' => 'Sang Pemimpi', 'description' => 'Ikal dan kawan-kawan bermimpi besar untuk mengubah nasib di Belitung.', 'price' => 75000.00, 'stock' => 20, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://upload.wikimedia.org/wikipedia/id/1/1d/Sang_Pemimpi.jpg', 'genre_id' => 1, 'author_id' => 1],
            ['id' => 39, 'title' => 'Edensor', 'description' => 'Ikal menjelajahi Eropa sambil mengejar mimpi dan cintanya.', 'price' => 78000.00, 'stock' => 18, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://upload.wikimedia.org/wikipedia/id/9/9d/Edensor.jpg', 'genre_id' => 1, 'author_id' => 1],
            ['id' => 40, 'title' => 'Maryamah Karpov', 'description' => 'Ikal kembali ke Belitung untuk menemukan cinta pertamanya.', 'price' => 82000.00, 'stock' => 15, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://upload.wikimedia.org/wikipedia/id/9/95/Maryamah_Karpov.jpg', 'genre_id' => 1, 'author_id' => 1],
            ['id' => 41, 'title' => 'Pulang', 'description' => 'Bujang mengemban tugas berbahaya di dunia hitam dan belajar tentang keluarga.', 'price' => 90000.00, 'stock' => 17, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1396014449i/22097895.jpg', 'genre_id' => 11, 'author_id' => 2],
            ['id' => 42, 'title' => 'Rindu', 'description' => 'Kisah beragam penumpang kapal haji yang menyimpan kerinduan mendalam.', 'price' => 85000.00, 'stock' => 19, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1403434042i/22589044.jpg', 'genre_id' => 7, 'author_id' => 2],
            ['id' => 43, 'title' => 'Ayah', 'description' => 'Kisah seorang ayah yang berjuang membesarkan anaknya seorang diri dengan penuh kasih.', 'price' => 88000.00, 'stock' => 22, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1441003824i/26198485.jpg', 'genre_id' => 1, 'author_id' => 2],
            ['id' => 44, 'title' => 'Perahu Kertas', 'description' => 'Kisah cinta Kugy dan Keenan yang penuh mimpi dan rintangan.', 'price' => 88000.00, 'stock' => 20, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://upload.wikimedia.org/wikipedia/id/a/a3/Perahu_Kertas.jpg', 'genre_id' => 7, 'author_id' => 6],
            ['id' => 45, 'title' => 'Rectoverso', 'description' => 'Sebelas cerita pendek tentang cinta yang saling berkaitan secara tersembunyi.', 'price' => 92000.00, 'stock' => 14, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1327943974i/6463649.jpg', 'genre_id' => 1, 'author_id' => 6],
            ['id' => 46, 'title' => 'Ranah 3 Warna', 'description' => 'Alif berjuang menimba ilmu di Bandung dan merantau ke negeri asing.', 'price' => 90000.00, 'stock' => 16, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1310394793i/9963580.jpg', 'genre_id' => 1, 'author_id' => 9],
            ['id' => 47, 'title' => 'Hujan', 'description' => 'Kisah cinta dua insan di era teknologi masa depan yang penuh kehilangan.', 'price' => 88000.00, 'stock' => 23, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1446197397i/26971989.jpg', 'genre_id' => 10, 'author_id' => 2],
            ['id' => 48, 'title' => 'Lelaki Harimau', 'description' => 'Kisah seorang pemuda yang terlibat dalam kekerasan dan mencari identitasnya.', 'price' => 95000.00, 'stock' => 11, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/isbn/9786020323176-L.jpg', 'genre_id' => 1, 'author_id' => 10],
            ['id' => 49, 'title' => 'Seperti Dendam Rindu Harus Dibayar Tuntas', 'description' => 'Kisah cinta dan balas dendam yang penuh ironi di Indonesia pasca-65.', 'price' => 95000.00, 'stock' => 9, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://covers.openlibrary.org/b/isbn/9786020320403-L.jpg', 'genre_id' => 1, 'author_id' => 10],
            ['id' => 50, 'title' => 'Guru Aini', 'description' => 'Perjuangan seorang guru matematika berbakat mengajar di pedalaman Sumatera.', 'price' => 85000.00, 'stock' => 12, 'file_path' => 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 'cover_photo' => 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1614165803i/56597148.jpg', 'genre_id' => 1, 'author_id' => 1],
        ]);

        // Distribute transactions: Jan=4, Feb=4, Mar=6, Apr=6
        DB::table('transactions')->insert([
            ['id' => 1,  'order_number' => 'ORD-001', 'customer_id' => 1,  'book_id' => 1,  'subtotal' => 63750.00,  'tax_amount' => 7500.00,  'shipping_cost' => 3750.00,  'total_amount' => 75000.00,  'status' => 'selesai',    'snap_token' => 'snap-a1b2c3d4e5f6', 'payment_type' => 'credit_card',  'created_at' => $rd(1, 3,  10), 'updated_at' => $rd(1, 3,  10)],
            ['id' => 2,  'order_number' => 'ORD-002', 'customer_id' => 2,  'book_id' => 3,  'subtotal' => 127500.00, 'tax_amount' => 15000.00, 'shipping_cost' => 7500.00,  'total_amount' => 150000.00, 'status' => 'dikirim',    'snap_token' => 'snap-b2c3d4e5f6g7', 'payment_type' => 'bank_transfer', 'created_at' => $rd(1, 8,  15), 'updated_at' => $rd(1, 8,  15)],
            ['id' => 3,  'order_number' => 'ORD-003', 'customer_id' => 4,  'book_id' => 2,  'subtotal' => 72250.00,  'tax_amount' => 8500.00,  'shipping_cost' => 4250.00,  'total_amount' => 85000.00,  'status' => 'selesai',    'snap_token' => 'snap-c3d4e5f6g7h8', 'payment_type' => 'gopay',        'created_at' => $rd(1, 18, 25), 'updated_at' => $rd(1, 18, 25)],
            ['id' => 4,  'order_number' => 'ORD-004', 'customer_id' => 5,  'book_id' => 5,  'subtotal' => 51000.00,  'tax_amount' => 6000.00,  'shipping_cost' => 3000.00,  'total_amount' => 60000.00,  'status' => 'dibayar',    'snap_token' => 'snap-d4e5f6g7h8i9', 'payment_type' => 'shopeepay',    'created_at' => $rd(1, 26, 28), 'updated_at' => $rd(1, 26, 28)],
            ['id' => 5,  'order_number' => 'ORD-005', 'customer_id' => 6,  'book_id' => 6,  'subtotal' => 80750.00,  'tax_amount' => 9500.00,  'shipping_cost' => 4750.00,  'total_amount' => 95000.00,  'status' => 'selesai',    'snap_token' => 'snap-e5f6g7h8i9j0', 'payment_type' => 'bank_transfer', 'created_at' => $rd(2, 2,  8),  'updated_at' => $rd(2, 2,  8)],
            ['id' => 6,  'order_number' => 'ORD-006', 'customer_id' => 1,  'book_id' => 1,  'subtotal' => 68000.00,  'tax_amount' => 8000.00,  'shipping_cost' => 4000.00,  'total_amount' => 80000.00,  'status' => 'dibatalkan', 'snap_token' => 'snap-f6g7h8i9j0k1', 'payment_type' => 'credit_card',  'created_at' => $rd(2, 9,  14), 'updated_at' => $rd(2, 9,  14)],
            ['id' => 7,  'order_number' => 'ORD-007', 'customer_id' => 7,  'book_id' => 7,  'subtotal' => 93500.00,  'tax_amount' => 11000.00, 'shipping_cost' => 5500.00,  'total_amount' => 110000.00, 'status' => 'selesai',    'snap_token' => 'snap-g7h8i9j0k1l2', 'payment_type' => 'gopay',        'created_at' => $rd(2, 16, 21), 'updated_at' => $rd(2, 16, 21)],
            ['id' => 8,  'order_number' => 'ORD-999', 'customer_id' => 4,  'book_id' => 5,  'subtotal' => 51000.00,  'tax_amount' => 6000.00,  'shipping_cost' => 3000.00,  'total_amount' => 60000.00,  'status' => 'dibayar',    'snap_token' => 'snap-h8i9j0k1l2m3', 'payment_type' => 'shopeepay',    'created_at' => $rd(2, 22, 28), 'updated_at' => $rd(2, 22, 28)],
            ['id' => 9,  'order_number' => 'ORD-008', 'customer_id' => 8,  'book_id' => 8,  'subtotal' => 89250.00,  'tax_amount' => 10500.00, 'shipping_cost' => 5250.00,  'total_amount' => 105000.00, 'status' => 'selesai',    'snap_token' => 'snap-i9j0k1l2m3n4', 'payment_type' => 'bank_transfer', 'created_at' => $rd(3, 2,  7),  'updated_at' => $rd(3, 2,  7)],
            ['id' => 10, 'order_number' => 'ORD-009', 'customer_id' => 9,  'book_id' => 10, 'subtotal' => 106250.00, 'tax_amount' => 12500.00, 'shipping_cost' => 6250.00,  'total_amount' => 125000.00, 'status' => 'dibayar',    'snap_token' => 'snap-j0k1l2m3n4o5', 'payment_type' => 'credit_card',  'created_at' => $rd(3, 8,  12), 'updated_at' => $rd(3, 8,  12)],
            ['id' => 11, 'order_number' => 'ORD-010', 'customer_id' => 11, 'book_id' => 11, 'subtotal' => 212500.00, 'tax_amount' => 25000.00, 'shipping_cost' => 12500.00, 'total_amount' => 250000.00, 'status' => 'selesai',    'snap_token' => 'snap-k1l2m3n4o5p6', 'payment_type' => 'gopay',        'created_at' => $rd(3, 13, 17), 'updated_at' => $rd(3, 13, 17)],
            ['id' => 12, 'order_number' => 'ORD-011', 'customer_id' => 12, 'book_id' => 12, 'subtotal' => 153000.00, 'tax_amount' => 18000.00, 'shipping_cost' => 9000.00,  'total_amount' => 180000.00, 'status' => 'dikirim',    'snap_token' => 'snap-l2m3n4o5p6q7', 'payment_type' => 'shopeepay',    'created_at' => $rd(3, 18, 22), 'updated_at' => $rd(3, 18, 22)],
            ['id' => 13, 'order_number' => 'ORD-012', 'customer_id' => 13, 'book_id' => 13, 'subtotal' => 76500.00,  'tax_amount' => 9000.00,  'shipping_cost' => 4500.00,  'total_amount' => 90000.00,  'status' => 'selesai',    'snap_token' => 'snap-m3n4o5p6q7r8', 'payment_type' => 'bank_transfer', 'created_at' => $rd(3, 23, 28), 'updated_at' => $rd(3, 23, 28)],
            ['id' => 14, 'order_number' => 'ORD-013', 'customer_id' => 14, 'book_id' => 14, 'subtotal' => 59500.00,  'tax_amount' => 7000.00,  'shipping_cost' => 3500.00,  'total_amount' => 70000.00,  'status' => 'selesai',    'snap_token' => 'snap-n4o5p6q7r8s9', 'payment_type' => 'credit_card',  'created_at' => $rd(3, 29, 31), 'updated_at' => $rd(3, 29, 31)],
            ['id' => 15, 'order_number' => 'ORD-014', 'customer_id' => 15, 'book_id' => 15, 'subtotal' => 114750.00, 'tax_amount' => 13500.00, 'shipping_cost' => 6750.00,  'total_amount' => 135000.00, 'status' => 'dibayar',    'snap_token' => 'snap-o5p6q7r8s9t0', 'payment_type' => 'gopay',        'created_at' => $rd(4, 2,  7),  'updated_at' => $rd(4, 2,  7)],
            ['id' => 16, 'order_number' => 'ORD-015', 'customer_id' => 16, 'book_id' => 16, 'subtotal' => 97750.00,  'tax_amount' => 11500.00, 'shipping_cost' => 5750.00,  'total_amount' => 115000.00, 'status' => 'selesai',    'snap_token' => 'snap-p6q7r8s9t0u1', 'payment_type' => 'shopeepay',    'created_at' => $rd(4, 8,  13), 'updated_at' => $rd(4, 8,  13)],
            ['id' => 17, 'order_number' => 'ORD-016', 'customer_id' => 17, 'book_id' => 17, 'subtotal' => 63750.00,  'tax_amount' => 7500.00,  'shipping_cost' => 3750.00,  'total_amount' => 75000.00,  'status' => 'dikirim',    'snap_token' => 'snap-q7r8s9t0u1v2', 'payment_type' => 'bank_transfer', 'created_at' => $rd(4, 14, 18), 'updated_at' => $rd(4, 14, 18)],
            ['id' => 18, 'order_number' => 'ORD-017', 'customer_id' => 18, 'book_id' => 18, 'subtotal' => 72250.00,  'tax_amount' => 8500.00,  'shipping_cost' => 4250.00,  'total_amount' => 85000.00,  'status' => 'dibayar',    'snap_token' => 'snap-r8s9t0u1v2w3', 'payment_type' => 'credit_card',  'created_at' => $rd(4, 19, 23), 'updated_at' => $rd(4, 19, 23)],
            ['id' => 19, 'order_number' => 'ORD-018', 'customer_id' => 19, 'book_id' => 19, 'subtotal' => 80750.00,  'tax_amount' => 9500.00,  'shipping_cost' => 4750.00,  'total_amount' => 95000.00,  'status' => 'selesai',    'snap_token' => 'snap-s9t0u1v2w3x4', 'payment_type' => 'gopay',        'created_at' => $rd(4, 24, 27), 'updated_at' => $rd(4, 24, 27)],
            ['id' => 20, 'order_number' => 'ORD-019', 'customer_id' => 20, 'book_id' => 20, 'subtotal' => 55250.00,  'tax_amount' => 6500.00,  'shipping_cost' => 3250.00,  'total_amount' => 65000.00,  'status' => 'dibayar',    'snap_token' => 'snap-t0u1v2w3x4y5', 'payment_type' => 'shopeepay',    'created_at' => $rd(4, 28, 30), 'updated_at' => $rd(4, 28, 30)],
        ]);
    }
}

